# -*- coding: utf-8 -*-
"""aasingment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NWlueAoCAhYoRbmRmRng-QEP6ox5SV_
"""

# Assingment 2
# this program about convert the temperatue (celsius to fahrenheit) and (fahrenheit to celsius):

# Writ menu because user's can understand easily

print("Temperature Converter Menu:")
print("1. Celsius to Fahrenheit")
print("2. Fahrenheit to Celsius")

#Ask the conversion type from user's
Select_menu = input("Enter your choice (1 or 2): ")

# Convert Celsius to Fahrenheit

if Select_menu == "1":
  # Ask the celsius temp from user

  celsius = float(input("Enter temperature in cesius: "))
  fahrenheit=( celsius * 9/5 )+32
  print(f"{celsius}°C is equal to {fahrenheit}°F")

  #convert fahrenheit to celsius

elif Select_menu =="2":

 # Ask the fahrenheit to celsius
 fahrenheit = float(input("Enter tmperature in fahrenheit:"))
 celsius = (fahrenheit - 32) * 5/9
 print(f"{fahrenheit} °F is equal to {celsius}°C.")

#show invalid result
else:
  print("Invalid: please choose an option again ( 1 , 2 )")
